---
platform: linux

image_resource:
  type: docker-image
  source:
    #repository: 192.168.100.1:5000/concourse-gradle
    #insecure_registries: [ "192.168.100.1:5000" ]
    repository: ((DOCKER_IMAGE))
    tag: latest


inputs:
  - name: resource-git
  - name: version

outputs:
  - name: artifact-dir

run:
  path: resource-git/ci/tasks/build-artifact.sh

params:
  DOCKER_IMAGE: ((DOCKER_IMAGE))