---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 192.168.100.1:5000/concourse-gradle
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/unit.sh

params:
  DOCKER_IMAGE: