---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: {{DOCKER_IMAGE}}
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/unit.sh

params:
  DOCKER_IMAGE: