---

# == Description
#
# This pipeline has only one simple Job
# The objective is just to build and deploy the app to PWS
#

jobs:
# Deploy it PWS
- name: job-deploy-to-pws
  plan:
  - get: resource-git
    trigger: true
  - task: task-build-artifact
    file: resource-git/ci/tasks/tiny-all-in-one.yml
    params:
      docker_image: ((DOCKER_IMAGE))
  - put: cf-deploy-production-app
    params:
      manifest: resource-git/manifest.yml
      current_app_name: ((CURRENT_APP_NAME))
      path: artifact-dir/spring-music*.jar

resources:
# Git Resource
- name: resource-git
  type: git
  source:
    uri: ((GIT_REPO))
    branch: master

# CF Resource for PROD
- name: cf-deploy-production-app
  type: cf
  source:
    api: ((CF_API))
    username: ((CF_USER))
    password: ((CF_PASSWD))
    organization: ((CF_ORG))
    space: ((CF_SPACE))
    skip_cert_check: true
